### ISSUE TITLE
Square for background color is not transparent

### ISSUE THREAD

**Issue by Zdele1** [kbladin/KalleWheel#16]
Square for background color is not transparent when picking color from the wheel. Makes it harder to judge which color i'm picking if it near the background color. 

Just to add, I love your attention to detail to make all secondary markings transparent when picking colors, great job there

Not transparent on square
![image](https://user-images.githubusercontent.com/64246807/81146848-5c440d80-8f79-11ea-9616-f88e9c2efd33.png)

Transparent on X
![image](https://user-images.githubusercontent.com/64246807/81146794-433b5c80-8f79-11ea-8687-f45a1e74edaf.png)

**Comment by kbladin** [comment]
None of the color glyphs are actually transparent. They take the same hue and chroma values as the color of the location on the wheel. That is done intentionally so that when modifying the lighness value it's still possible to see the difference in lightness of individual colors. One thing that could be done to make this a little easier would be to simply render the foreground color glyph on top of the background color glyph instead of the other way around.

**Comment by Zdele1** [comment]
yes, that's what i meant, rendering foreground color glyph on top would fix this - it's already rendered on top of all the other glyphs, which makes it easier to pick colors since secondary glyphs dont obscure it
