### ISSUE TITLE
Make X togglable

### ISSUE THREAD

**Issue by kbladin** [kbladin/KalleWheel#5]
X in the middle can be togglable as it sometimes can be distracting

**Comment by Zdele1** [comment]
Just to update, I found X to be pretty useful when picking greys for a neutral paintings, since it makes it easier to judge on which part of the color wheel the grey i'm picking belongs, but it's not so useful in limited gamut paintings.

Also i love how you made it transparent when moving color picker over it, great job!

A option to hide it might go in this menu to reduce UI clutter

![image](https://user-images.githubusercontent.com/64246807/81148068-df666300-8f7b-11ea-9940-3a84d60779f8.png)
